# collect.ps1 - MDM fleet data collector
# Author: Sulemana Akuantu Abdul Jalil (FCM.41.018.245.23)
#
# Enumerates the ADB-connected fleet, collects device state for every online
# device, evaluates it against the policy baseline and writes:
#   - src/dashboard/data/devices.js   (data consumed by the dashboard)
#   - evidence/logs/devices-<timestamp>.json  (raw snapshot)
#
# Usage:  powershell -ExecutionPolicy Bypass -File collect.ps1

$ErrorActionPreference = "Continue"

$root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)   # mdm-dashboard/
$adb = Join-Path $env:LOCALAPPDATA "Android\Sdk\platform-tools\adb.exe"
$policyPath = Join-Path $root "scripts\policies\policy.json"
$dataDir = Join-Path $root "src\dashboard\data"
$logDir = Join-Path $root "evidence\logs"

Import-Module (Join-Path $PSScriptRoot "mdm.ps1") -Force

if (-not (Test-Path $adb)) { throw "adb not found at $adb" }
$policy = Get-Content $policyPath -Raw | ConvertFrom-Json

# 1) Enumerate online devices
$raw = & $adb devices | Out-String
$devices = @()
foreach ($line in ($raw -split "\r?\n")) {
    if ($line -match "^([\w\-\.:]+)\s+device$") {
        $devices += $Matches[1]
    }
}
if ($devices.Count -eq 0) {
    Write-Host "No online ADB devices found. Start the emulators first." -ForegroundColor Yellow
    exit 1
}
Write-Host "Fleet discovered: $($devices -join ', ')" -ForegroundColor Cyan

# 2) Collect per-device reports
$reports = @()
foreach ($serial in $devices) {
    Write-Host "Collecting state for $serial ..." -NoNewline
    try {
        Enable-AdbRoot -Serial $serial
        $rep = Get-DeviceReport -Serial $serial -Policy $policy
        $reports += $rep
        Write-Host " done (score $($rep.compliance.score)%)" -ForegroundColor Green
    } catch {
        Write-Host " FAILED: $($_.Exception.Message)" -ForegroundColor Red
    }
}

# 3) Build dashboard payload
$payload = [PSCustomObject]@{
    generatedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    agent       = "OrgLab MDM Agent (ADB control channel)"
    agentVersion = "1.0.0"
    policy      = $policy
    devices     = $reports
}

# 4) Write devices.js for the dashboard
$json = $payload | ConvertTo-Json -Depth 12
$js = "// Auto-generated by collect.ps1 - do not edit by hand.`n// Generated: $((Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss UTC'))`nwindow.MDM_DATA = $json;`n"
$jsOut = Join-Path $dataDir "devices.js"
Set-Content -LiteralPath $jsOut -Value $js -Encoding UTF8

# 5) Write raw JSON snapshot to evidence/logs
$stamp = (Get-Date).ToString("yyyyMMdd-HHmmss")
$jsonOut = Join-Path $logDir "devices-$stamp.json"
Set-Content -LiteralPath $jsonOut -Value ($json | ConvertFrom-Json | ConvertTo-Json -Depth 12) -Encoding UTF8

Write-Host ""
Write-Host "Dashboard data  -> $jsOut" -ForegroundColor Green
Write-Host "Raw snapshot    -> $jsonOut" -ForegroundColor Green
Write-Host ""
foreach ($d in $reports) {
    $color = switch ($d.compliance.status) { "COMPLIANT" { "Green" } "AT RISK" { "Yellow" } default { "Red" } }
    Write-Host ("  {0,-28} {1,6}%  {2}" -f $d.identity.model, $d.compliance.score, $d.compliance.status) -ForegroundColor $color
}
